const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));

async function testDynamicProgress() {
  console.log('🎯 Testing Dynamic Progress System...\n');
  
  const testCases = [
    {
      name: 'Amazon Senior Backend Interview',
      prompt: 'I have an interview next month with Amazon for Senior Backend role'
    },
    {
      name: 'Google Frontend Interview',
      prompt: 'I have an interview next month with Google for Senior Frontend role'
    }
  ];

  for (let i = 0; i < testCases.length; i++) {
    const testCase = testCases[i];
    console.log(`${i + 1}. Testing: ${testCase.name}`);
    console.log(`   Input: "${testCase.prompt}"`);
    
    try {
      const startTime = Date.now();
      const response = await fetch('http://localhost:4000/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: testCase.prompt })
      });
      
      const data = await response.json();
      const endTime = Date.now();
      const duration = endTime - startTime;
      
      console.log(`   ✅ Response Type: ${data.type}`);
      console.log(`   ⏱️  Duration: ${duration}ms`);
      
      if (data.type === 'interview_prep') {
        console.log(`   🎯 Session ID: ${data.sessionId}`);
        console.log(`   📋 Actions Created: ${data.actions?.length || 0}`);
        console.log(`   📝 Summary Generated: ${data.summary ? 'Yes' : 'No'}`);
        console.log(`   🔄 Progress Updates: ${data.progress?.length || 0} steps`);
        
        if (data.progress) {
          console.log('   📊 Dynamic Progress Flow:');
          data.progress.forEach((step, index) => {
            console.log(`      ${index + 1}. ${step}`);
          });
        }
        
        // Check for acknowledgment
        if (data.progress && data.progress[0] === "Working on your request...") {
          console.log('   ✅ Acknowledgment shown correctly');
        }
        
        // Check for dynamic progress messages
        const hasDynamicMessages = data.progress && data.progress.some(msg => 
          msg.includes('📅') || msg.includes('📚') || msg.includes('📋') || 
          msg.includes('🎯') || msg.includes('📧')
        );
        
        if (hasDynamicMessages) {
          console.log('   ✅ Dynamic progress messages generated by AI');
        }
        
        // Check for clean summary format
        if (data.response && data.response.includes('Things I have already done for you')) {
          console.log('   ✅ Clean summary format with 2 sections');
        }
        
        // Check if it's a complete response
        if (data.actions && data.actions.length >= 5) {
          console.log('   🎉 Complete Dynamic Interview Prep Plan Generated!');
        } else {
          console.log('   ℹ️  Basic response (needs more info)');
        }
      } else {
        console.log(`   💬 Response: ${data.response?.substring(0, 100)}...`);
      }
      
    } catch (error) {
      console.log(`   ❌ Error: ${error.message}`);
    }
    
    console.log('   ' + '-'.repeat(40));
  }
  
  console.log('\n🎉 Dynamic Progress System is working!');
  console.log('\n✅ New Features:');
  console.log('- AI-driven strategy generation');
  console.log('- Dynamic progress messages per action');
  console.log('- Company/role-specific messaging');
  console.log('- Real-time progress updates');
  console.log('- No hardcoded progress messages');
  console.log('\nTo test the UI:');
  console.log('1. Open http://localhost:3000');
  console.log('2. Click on "Chat" tab');
  console.log('3. Try: "I have an interview next month with Amazon for Senior Backend role"');
  console.log('4. Watch the AI-generated dynamic progress!');
}

testDynamicProgress(); 